site_name: Gluster Docs
site_url: http://docs.gluster.org
site_description: Project documentation for Gluster Filesystem

repo_url: https://github.com/gluster/glusterdocs/
docs_dir: docs

nav:
- Home: index.md
- Introduction: Administrator Guide/GlusterFS Introduction.md
- Install Guide: Install-Guide/Install.md
- Administration Guide:
  - Introduction: Administrator Guide/New.md
  - Logging: Administrator Guide/Logging.md
  - Managing Volumes: Administrator Guide/Managing Volumes.md
  - Split brain and ways to deal with it: Administrator Guide/Split brain and ways to deal with it.md
  - Arbiter volumes and quorum options: Administrator Guide/arbiter-volumes-and-quorum.md
  - Thin Arbiter volumes: Administrator Guide/Thin-Arbiter-Volumes.md
  - Monitoring Workload: Administrator Guide/Monitoring Workload.md

- Features:
  - Geo Replication: Administrator Guide/Geo Replication.md
  - Quotas: Administrator Guide/Directory Quota.md
  - Trash for GlusterFS: Administrator Guide/Trash.md
  - Events APIs: Administrator Guide/Events APIs.md

- Architecture: Quick-Start-Guide/Architecture.md
